import copy
from typing import Any, List

# --- Type Definitions ---
Action = str
State = dict[str, Any]
PlayerObservation = dict[str, Any]

# --- Constants ---
GRID_SIZE = 5
WIN_POS = (2, 2)
MAX_TURNS = 50
PLAYERS = [0, 1]

def get_player_name(player_id: int) -> str:
    """Returns the name of the player."""
    if player_id == -4:
        return "terminal"
    return str(player_id)

def get_initial_state() -> State:
    """Returns the initial state of the game."""
    return {
        "board": {
            "0_0": 0, "0_4": 0,  # Player 0 start positions
            "4_0": 1, "4_4": 1   # Player 1 start positions
        },
        "stunned_units": {},     # Key: unit_pos string, Value: turn_stunned
        "current_player": 0,
        "turn_count": 0,
        "history": [],
        "status": "ongoing",
        "winner": None
    }

def get_current_player(state: State) -> int:
    """Returns current player (0 or 1), or -4 for terminal state."""
    if state["status"] != "ongoing":
        return -4
    return state["current_player"]

def _is_adjacent(pos1: tuple[int, int], pos2: tuple[int, int]) -> bool:
    """Checks if two positions are adjacent (orthogonally or diagonally)."""
    r1, c1 = pos1
    r2, c2 = pos2
    return max(abs(r1 - r2), abs(c1 - c2)) == 1

def _parse_pos(pos_str: str) -> tuple[int, int]:
    r, c = map(int, pos_str.split("_"))
    return r, c

def _format_pos(r: int, c: int) -> str:
    return f"{r}_{c}"

def get_legal_actions(state: State) -> List[Action]:
    """Returns legal actions. Filters out stunned units."""
    if state["status"] != "ongoing":
        return []

    player = state["current_player"]
    actions = []
    
    # Identify player's units
    my_units = [pos for pos, owner in state["board"].items() if owner == player]
    
    can_move = False
    
    for unit_pos_str in my_units:
        # Check Stun Status
        # A unit is stunned if it is in the stunned_units dict AND 
        # the current turn is the immediate turn after it was stunned.
        # Logic: If stunned at turn T, it cannot move at turn T+1.
        if unit_pos_str in state["stunned_units"]:
            stun_turn = state["stunned_units"][unit_pos_str]
            if state["turn_count"] <= stun_turn + 1:
                continue # Unit is skipped (Stunned)

        r, c = _parse_pos(unit_pos_str)
        
        # Generate moves (all 8 directions)
        for dr in [-1, 0, 1]:
            for dc in [-1, 0, 1]:
                if dr == 0 and dc == 0:
                    continue
                
                nr, nc = r + dr, c + dc
                
                # Bounds check
                if 0 <= nr < GRID_SIZE and 0 <= nc < GRID_SIZE:
                    target_pos_str = _format_pos(nr, nc)
                    
                    # Occupancy check (cannot move onto ANY unit)
                    if target_pos_str not in state["board"]:
                        actions.append(f"move ({r},{c}) to ({nr},{nc})")
                        can_move = True

    if not can_move:
        return ["pass"]
        
    return sorted(actions)

def apply_action(state: State, action: Action) -> State:
    """Returns the new state after an action. Handles movement, stuns, and wins."""
    # Enforce Immutability
    new_state = copy.deepcopy(state)
    
    if action == "pass":
        new_state["current_player"] = 1 - new_state["current_player"]
        new_state["turn_count"] += 1
        
        # Draw Condition check on pass? 
        # (Usually draw is max turns, but we strictly check max turns below)
        if new_state["turn_count"] >= MAX_TURNS:
            new_state["status"] = "draw"
            new_state["current_player"] = -4
            
        return new_state

    # Parse Action: "move (r1,c1) to (r2,c2)"
    # We assume strict syntax as generated by get_legal_actions
    parts = action.split()
    origin_str = parts[1].strip("(),")
    target_str = parts[3].strip("(),")
    
    r1, c1 = map(int, origin_str.split(","))
    r2, c2 = map(int, target_str.split(","))
    
    current_player = new_state["current_player"]
    origin_key = _format_pos(r1, c1)
    target_key = _format_pos(r2, c2)
    
    # 1. Move Unit
    del new_state["board"][origin_key]
    new_state["board"][target_key] = current_player
    
    # 2. Check Win Condition (Occupying Center)
    if (r2, c2) == WIN_POS:
        new_state["status"] = "won"
        new_state["winner"] = current_player
        new_state["current_player"] = -4
        return new_state
    
    # 3. Apply Stun Logic
    # Check for adjacent opponent units
    opponent = 1 - current_player
    opponent_units = [pos for pos, owner in new_state["board"].items() if owner == opponent]
    
    for opp_pos_str in opponent_units:
        opp_r, opp_c = _parse_pos(opp_pos_str)
        if _is_adjacent((r2, c2), (opp_r, opp_c)):
            # Apply Stun: Mark the turn it happened.
            # It implies the unit cannot move on the opponent's immediate next turn.
            new_state["stunned_units"][opp_pos_str] = new_state["turn_count"]

    # 4. Clean up old stuns (Optional for memory, but good for logic)
    # Remove entries from stun dict if they are expired to keep state clean
    active_stuns = {
        k: v for k, v in new_state["stunned_units"].items() 
        if new_state["turn_count"] <= v + 1
    }
    new_state["stunned_units"] = active_stuns

    # 5. Update Global State
    new_state["turn_count"] += 1
    
    # Check Draw (Max Turns)
    if new_state["turn_count"] >= MAX_TURNS:
        new_state["status"] = "draw"
        new_state["current_player"] = -4
    else:
        new_state["current_player"] = opponent
        
    return new_state

def get_rewards(state: State) -> List[float]:
    """Returns rewards. Zero-sum."""
    if state["status"] == "ongoing":
        return [0.0, 0.0]
    
    if state["status"] == "draw":
        return [0.0, 0.0]
        
    if state["status"] == "won":
        winner = state["winner"]
        return [1.0, -1.0] if winner == 0 else [-1.0, 1.0]
        
    return [0.0, 0.0]

def get_observations(state: State) -> List[PlayerObservation]:
    """Perfect information: Both players see the full state."""
    return [state, state]